import type { ProblemFixture } from "./types"

export const headingProblemFixtures = [
  {
    problemId: "heading-project-notes",
    kind: "canonical",
    source: "# Project notes",
    expectedStatus: "perfect",
    expectedReviewIds: [],
  },
  {
    problemId: "heading-project-notes",
    kind: "alternate",
    source: "# Project notes #",
    expectedStatus: "perfect",
    expectedReviewIds: [],
  },
  {
    problemId: "heading-project-notes",
    kind: "missing",
    source: "Project notes",
    expectedStatus: "fail",
    expectedFeedbackId: "use-h1-heading",
  },
  {
    problemId: "heading-project-notes",
    kind: "malformed",
    source: "#Project notes",
    expectedStatus: "fail",
    expectedFeedbackId: "space-after-hash",
  },
  {
    problemId: "heading-project-notes",
    kind: "matched-with-refinement",
    source: "# Project notes\n\n# Details",
    expectedStatus: "matched",
    expectedReviewIds: ["one-document-title"],
  },
  {
    problemId: "heading-project-notes",
    kind: "perfect",
    source: "# Project notes",
    expectedStatus: "perfect",
    expectedReviewIds: [],
  },
  {
    problemId: "heading-weekend-guide",
    kind: "canonical",
    source: "# Weekend guide",
    expectedStatus: "perfect",
    expectedReviewIds: [],
  },
  {
    problemId: "heading-weekend-guide",
    kind: "alternate",
    source: "# Weekend guide #",
    expectedStatus: "perfect",
    expectedReviewIds: [],
  },
  {
    problemId: "heading-weekend-guide",
    kind: "missing",
    source: "Weekend guide",
    expectedStatus: "fail",
    expectedFeedbackId: "use-h1-heading",
  },
  {
    problemId: "heading-weekend-guide",
    kind: "malformed",
    source: "#Weekend guide",
    expectedStatus: "fail",
    expectedFeedbackId: "space-after-hash",
  },
  {
    problemId: "heading-weekend-guide",
    kind: "matched-with-refinement",
    source: "# Weekend guide\n\n# Details",
    expectedStatus: "matched",
    expectedReviewIds: ["one-document-title"],
  },
  {
    problemId: "heading-weekend-guide",
    kind: "perfect",
    source: "# Weekend guide",
    expectedStatus: "perfect",
    expectedReviewIds: [],
  },
  {
    problemId: "heading-reading-list",
    kind: "canonical",
    source: "# Summer reading list",
    expectedStatus: "perfect",
    expectedReviewIds: [],
  },
  {
    problemId: "heading-reading-list",
    kind: "alternate",
    source: "# Summer reading list #",
    expectedStatus: "perfect",
    expectedReviewIds: [],
  },
  {
    problemId: "heading-reading-list",
    kind: "missing",
    source: "Summer reading list",
    expectedStatus: "fail",
    expectedFeedbackId: "use-h1-heading",
  },
  {
    problemId: "heading-reading-list",
    kind: "malformed",
    source: "#Summer reading list",
    expectedStatus: "fail",
    expectedFeedbackId: "space-after-hash",
  },
  {
    problemId: "heading-reading-list",
    kind: "matched-with-refinement",
    source: "# Summer reading list\n\n# Details",
    expectedStatus: "matched",
    expectedReviewIds: ["one-document-title"],
  },
  {
    problemId: "heading-reading-list",
    kind: "perfect",
    source: "# Summer reading list",
    expectedStatus: "perfect",
    expectedReviewIds: [],
  },
] as const satisfies readonly ProblemFixture[]
