import { readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"
import type { Blockquote, RootContent } from "mdast"
import {
  acceptsGuidedSyntaxInput,
  deriveSyntaxCheckpoints,
  syntaxCheckpointTerms,
} from "../src/guided/guidedSyntax"
import { parseMarkdownSource } from "../src/markdown/parser"

const separators = ["", " ", "  ", "\t", " \t", "\t ", "\t\t"] as const

export type MarkdownNotationMatrixRow = {
  outer: string
  inner: string
  source: string
  parserOpensNestedQuote: boolean
  blankAppears: boolean
  gradesCanonicalInput: boolean
  reason: string
}

function parserOpensNestedQuote(source: string): boolean {
  const outer = parseMarkdownSource(source).children.find(
    (node): node is Blockquote => node.type === "blockquote",
  )
  return Boolean(
    outer?.children.some((node: RootContent) => node.type === "blockquote"),
  )
}

export function buildMarkdownNotationMatrix(): MarkdownNotationMatrixRow[] {
  return separators.flatMap((outer) =>
    separators.map((inner) => {
      const source = `>${outer}>${inner}deep`
      const parserOpened = parserOpensNestedQuote(source)
      const checkpoint = deriveSyntaxCheckpoints(source, "").find((candidate) =>
        syntaxCheckpointTerms(candidate).includes("quote inside a quote"),
      )
      const blankAppears = Boolean(checkpoint)
      const gradesCanonicalInput = Boolean(
        checkpoint &&
          !checkpoint.canonicalInput.includes("\t") &&
          acceptsGuidedSyntaxInput(checkpoint, checkpoint.canonicalInput),
      )
      const reason = !parserOpened
        ? "CommonMark expands the two outer tabs to indented code, so the AST has no inner blockquote."
        : !blankAppears
          ? "The parser opens the quote, but the outer marker whitespace contains a tab; the product leaves it locked because a visually identical space answer would not grade."
          : "—"
      return {
        outer,
        inner,
        source,
        parserOpensNestedQuote: parserOpened,
        blankAppears,
        gradesCanonicalInput,
        reason,
      }
    }),
  )
}

function visible(value: string): string {
  return value.replaceAll(" ", "SP").replaceAll("\t", "TAB") || "none"
}

function verdict(value: boolean): string {
  return value ? "yes" : "no"
}

export function renderMarkdownNotationMatrix(): string {
  const rows = buildMarkdownNotationMatrix()
  const parserCount = rows.filter((row) => row.parserOpensNestedQuote).length
  const blankCount = rows.filter((row) => row.blankAppears).length
  const gradedCount = rows.filter((row) => row.gradesCanonicalInput).length
  const tableRows = rows.map(
    (row, index) =>
      `| ${index + 1} | ${visible(row.outer)} | ${visible(row.inner)} | \`${row.source.replaceAll(" ", "<SP>").replaceAll("\t", "<TAB>")}\` | ${verdict(row.parserOpensNestedQuote)} | ${verdict(row.blankAppears)} | ${verdict(row.gradesCanonicalInput)} | ${row.reason} |`,
  )

  return `# Nested blockquote notation matrix

Generated by \`npx tsx scripts/markdownNotationMatrix.ts --write\` from the product's actual GFM parser, guided-card generator, and grader. Do not edit the table by hand.

- Forms evaluated: ${rows.length}
- Parser opens an inner blockquote: ${parserCount}
- Guided blank appears: ${blankCount}
- Canonical visible answer grades: ${gradedCount}
- Remaining forms: ${rows.length - gradedCount}; every one is an AST boundary, not a failed blank or grader path.

\`SP\` means one literal space and \`TAB\` means one literal tab.

| # | outer separator | inner separator | source | parser opens | blank appears | grades | remaining reason |
| -: | --- | --- | --- | :---: | :---: | :---: | --- |
${tableRows.join("\n")}
`
}

export const markdownNotationMatrixPath = resolve(
  process.cwd(),
  "docs/verification/markdown-notation-matrix.md",
)

if (process.argv.includes("--write")) {
  writeFileSync(markdownNotationMatrixPath, renderMarkdownNotationMatrix())
} else if (process.argv.includes("--check")) {
  const current = readFileSync(markdownNotationMatrixPath, "utf8")
  if (current !== renderMarkdownNotationMatrix()) {
    throw new Error(
      "Markdown notation matrix is stale; run npx tsx scripts/markdownNotationMatrix.ts --write",
    )
  }
}
